### ISSUE TITLE
ModuleNotFoundError: No module named 'recommender'

### ISSUE THREAD

**Issue by bayismet** [CVxTz/recommender_transformer#1]
Hello there!

I'm trying to run this code in W10. I setup the docker but when I click to run in vscode, it gives me the following error:

`C:\Users\Karras>C:/Python39/python.exe d:/workspaces/recommender_transformer/recommender/training.py
Traceback (most recent call last):
  File "d:\workspaces\recommender_transformer\recommender\training.py", line 11, in <module>
    from recommender.models import Recommender
ModuleNotFoundError: No module named 'recommender'`

Thanks!

**Comment by CVxTz** [comment]
Hey,
I don't use windows so I can't help you.
Best of luck,
