### ISSUE TITLE
Not found "recommender.ckpt"

### ISSUE THREAD

**Issue by sensinthanhan** [CVxTz/recommender_transformer#2]
model_path = "/home/jenazzad/PycharmProjects/recommender_transformer/recommender_models/recommender.ckpt"
Following this line, i search on your github but not found recommender.ckpt file, i'm newer with machine learning, i don't know what is this file, you forgot put it into github or i have to do something to get it?  Thanks for your help!

**Comment by kappek** [comment]
same here

**Comment by CVxTz** [comment]
Hello ! 
I did not save the model. You can train your own easily using the code.

Best,
