### ISSUE TITLE
request for 'recommender.ckpt' file

### ISSUE THREAD

**Issue by SamPraxMag** [CVxTz/recommender_transformer#4]
I'm unable to generate the 'recommender.ckpt' file from the ipynb files you have provided, maybe I'm not getting the trick to execute and generate it from your set of codes, 

Please provide the file and that will be useful in understanding the use case even better.

**Comment by ankitkr3** [comment]
hi @SamPraxMag are you able to do it?

**Comment by CVxTz** [comment]
the training happens here: https://github.com/CVxTz/recommender_transformer/blob/main/recommender/training.py
